/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  adcSidebar: [{type: 'autogenerated', dirName: 'adc'}],
  wafSidebar: [{type: 'autogenerated', dirName: 'waf'}],
  communitySidebar: [{type: 'autogenerated', dirName: 'community-waf'}],
  ddosSidebar: [{type: 'autogenerated', dirName: 'ddos'}],
  llbSidebar: [{type: 'autogenerated', dirName: 'llb'}],
  gslbSidebar: [{type: 'autogenerated', dirName: 'gslb'}],
  sslVPNSidebar: [{type: 'autogenerated', dirName: 'ssl-vpn'}],
  saasSidebar: [{type: 'autogenerated', dirName: 'saas'}],
};

module.exports = sidebars;
