/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */

const sidebars = {
  sidebar: [{
    type: 'html',
    value: '',
    defaultStyle: true,
    className: 'sidebar-title', // Use the default menu item styling
  },{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
